export const TICKERS: Record<string, { name: string; description: string }> = {
  SPY: { name: "SPY", description: "SPDR S&P 500 ETF Trust" },
  QQQ: { name: "QQQ", description: "Invesco QQQ Trust (Nasdaq 100)" },
  VOO: { name: "VOO", description: "Vanguard S&P 500 ETF" },
  VTI: { name: "VTI", description: "Vanguard Total Stock Market ETF" },
  IWM: { name: "IWM", description: "iShares Russell 2000 ETF" },
  TSLA: { name: "TSLA", description: "Tesla, Inc." },
  NVDA: { name: "NVDA", description: "NVIDIA Corporation" },
  AAPL: { name: "AAPL", description: "Apple Inc." },
  AMZN: { name: "AMZN", description: "Amazon.com, Inc." },
  MSFT: { name: "MSFT", description: "Microsoft Corporation" },
  META: { name: "META", description: "Meta Platforms, Inc." },
  GOOG: { name: "GOOG", description: "Alphabet Inc." },
  GOOGL: { name: "GOOGL", description: "Alphabet Inc. (Class A)" },
  AMD: { name: "AMD", description: "Advanced Micro Devices, Inc." },
  PLTR: { name: "PLTR", description: "Palantir Technologies Inc." },
  SOFI: { name: "SOFI", description: "SoFi Technologies, Inc." },
  COIN: { name: "COIN", description: "Coinbase Global, Inc." },
  NIO: { name: "NIO", description: "NIO Inc." },
  RIVN: { name: "RIVN", description: "Rivian Automotive, Inc." },
  JPM: { name: "JPM", description: "JPMorgan Chase & Co." },
  V: { name: "V", description: "Visa Inc." },
  DIS: { name: "DIS", description: "The Walt Disney Company" },
  NFLX: { name: "NFLX", description: "Netflix, Inc." },
  CRM: { name: "CRM", description: "Salesforce, Inc." },
  UBER: { name: "UBER", description: "Uber Technologies, Inc." },
  SHOP: { name: "SHOP", description: "Shopify Inc." },
  XYZ: { name: "XYZ", description: "Block, Inc." },
  SNAP: { name: "SNAP", description: "Snap Inc." },
  ROKU: { name: "ROKU", description: "Roku, Inc." },
  PYPL: { name: "PYPL", description: "PayPal Holdings, Inc." },
  WMT: { name: "WMT", description: "Walmart Inc." },
  KO: { name: "KO", description: "The Coca-Cola Company" },
  PEP: { name: "PEP", description: "PepsiCo, Inc." },
  COST: { name: "COST", description: "Costco Wholesale Corporation" },
  BA: { name: "BA", description: "The Boeing Company" },
  XOM: { name: "XOM", description: "Exxon Mobil Corporation" },
  JNJ: { name: "JNJ", description: "Johnson & Johnson" },
  GME: { name: "GME", description: "GameStop Corp." },
  AMC: { name: "AMC", description: "AMC Entertainment Holdings, Inc." },
  LCID: { name: "LCID", description: "Lucid Group, Inc." },
  MARA: { name: "MARA", description: "Marathon Digital Holdings, Inc." },
  ARM: { name: "ARM", description: "Arm Holdings plc" },
  SMCI: { name: "SMCI", description: "Super Micro Computer, Inc." },
};

export const TICKER_SLUGS = Object.keys(TICKERS);
